package com.baybin.phone

/**
 * Display language only. The rules, the logged bin name, and the logged reason stay English.
 * A reason with no Chinese line below is shown in English, so an instruction is never dropped.
 */
object Lang {

    fun zh(lang: String) = lang != "en"

    fun s(lang: String, key: String): String = (if (zh(lang)) ZH else EN).getValue(key)

    /** The official English reason, or the same instruction in Chinese. */
    fun reason(text: String, lang: String): String {
        if (!zh(lang)) return text
        REASON[text]?.let { return it }
        MIGHT.matchEntire(text)?.let { return "可能是${it.groupValues[1]}。再靠近一点，按一下。" }
        NO_RULE.matchEntire(text)?.let { return "${it.groupValues[1]}：${it.groupValues[2]}没有说清。" }
        return text
    }

    /**
     * Second line on the lens: the item's short name, so the wearer sees what was recognized.
     * No catalog name (the model wasn't sure, or there is no item) keeps the reason.
     * The bin word is separate. This does not choose a bin.
     */
    fun lensDetail(itemId: String?, englishName: String?, line2: String, lang: String): String {
        if (englishName == null) return reason(line2, lang)
        return if (zh(lang)) ITEM_ZH[itemId] ?: englishName else englishName
    }

    private val MIGHT = Regex("Might be (.+)\\. Look closer, tap again\\.")
    private val NO_RULE = Regex("(.+): no clear (.+) rule")

    private val ZH = mapOf(
        "title" to "湾区垃圾分类",
        "hint_cupertino" to "蓝桶回收  ·  绿桶厨余  ·  灰桶填埋",
        "hint_sj" to "蓝桶回收  ·  黑桶垃圾  ·  绿桶庭院",
        "hint_paloalto" to "蓝桶回收  ·  绿桶厨余  ·  黑桶垃圾",
        "hint_losaltos" to "蓝桶回收  ·  绿桶厨余  ·  灰桶垃圾",
        "scan" to "搜索眼镜",
        "connect" to "连接眼镜",
        "connect_other" to "换一副",
        "connected_btn" to "已连接",
        "reconnect" to "重连",
        "gallery" to "相册",
        "official" to "官方页面",
        "tap_connect" to "点一下连接",
        "glasses_name" to "眼镜",
        "settings" to "设置",
        "settings_back" to "返回",
        "settings_note" to "这台手机连着眼镜。密钥只留在手机上，用来识别，眼镜里不保存。",
        "key_hint" to "填你自己的千问密钥",
        "key_replace" to "填新的密钥就会换掉",
        "key_save" to "保存密钥",
        "key_set" to "密钥只在这台手机里，安装包里没有",
        "key_missing" to "还没填密钥。填上之后才会识别",
        "connected" to "眼镜已连接",
        "connecting" to "正在连接眼镜",
        "scanning" to "正在搜索眼镜",
        "failed_app" to "眼镜上的 BayBin 还没打开",
        "failed_none" to "没连上，先搜索眼镜",
        "disconnected" to "眼镜未连接",
        "glasses_ver" to "眼镜端 %s",
        "first_use" to "第一次：点下面的大按钮。只找到一副时会自己连上。",
        "paired_hint" to "点「连接眼镜」就连上。要换一副，点旁边的按钮。",
        "throw" to "扔进",
        "working" to "识别中…",
        "how" to "怎么用",
        "no_result" to "还没有结果",
        "how_body" to "先选 California，再选下面的城市。眼镜对准要扔的东西，戒指右键拍照，左键退出。没有眼镜时，用相册选一张照片。",
        "log" to "记录",
        "log_hide" to "收起记录",
        "photo" to "刚看过的照片",
        "source_glasses" to "眼镜",
        "source_gallery" to "相册",
        "no_pair" to "还没配过眼镜，先点「搜索眼镜」",
        "gallery_closed" to "相册打不开",
        "gallery_empty" to "相册没有返回照片",
        "no_bt" to "没有蓝牙权限，连不上眼镜（相册测试不受影响）",
        "notify" to "连着眼镜。右键拍照，左键退出",
    )

    private val EN = mapOf(
        "title" to "BayBin",
        "hint_cupertino" to "Blue recycling  ·  Green organics  ·  Gray landfill",
        "hint_sj" to "Blue-lid recycling  ·  Black garbage  ·  Green yard",
        "hint_paloalto" to "Blue recycling  ·  Green compost  ·  Black garbage",
        "hint_losaltos" to "Blue recycling  ·  Green organics  ·  Gray garbage",
        "scan" to "Find glasses",
        "connect" to "Connect glasses",
        "connect_other" to "Another pair",
        "connected_btn" to "Connected",
        "reconnect" to "Reconnect",
        "gallery" to "Gallery",
        "official" to "Official page",
        "tap_connect" to "Tap to connect",
        "glasses_name" to "Glasses",
        "settings" to "Settings",
        "settings_back" to "Back",
        "settings_note" to "This phone connects to the glasses. The key stays on the phone and names the item. The glasses do not keep it.",
        "key_hint" to "Your own Qwen key",
        "key_replace" to "Type a new key to replace the saved one",
        "key_save" to "Save key",
        "key_set" to "Key stays on this phone. It is not in the app package",
        "key_missing" to "No key yet. Recognition waits until you add yours",
        "connected" to "Glasses connected",
        "connecting" to "Connecting",
        "scanning" to "Searching",
        "failed_app" to "Open BayBin on the glasses",
        "failed_none" to "Not connected. Find the glasses first",
        "disconnected" to "Glasses not connected",
        "glasses_ver" to "Glasses %s",
        "first_use" to "First time: tap the big button. One pair connects by itself.",
        "paired_hint" to "Tap Connect glasses. To switch, tap Another pair.",
        "throw" to "Put it in",
        "working" to "Looking…",
        "how" to "How to",
        "no_result" to "No result yet",
        "how_body" to "Pick California, then a city below it. On the glasses, aim and press the ring's right key. The left key exits. Or pick a photo from the gallery.",
        "log" to "Log",
        "log_hide" to "Hide log",
        "photo" to "Last photo",
        "source_glasses" to "Glasses",
        "source_gallery" to "Gallery",
        "no_pair" to "No glasses paired yet. Tap Find glasses",
        "gallery_closed" to "Gallery won't open",
        "gallery_empty" to "Gallery returned no photo",
        "no_bt" to "No Bluetooth permission, so the glasses can't connect. Gallery still works",
        "notify" to "Glasses connected. Right key scans, left key exits",
    )

    /** Exact English reason from the city rules → the same instruction in Chinese. */
    private val REASON = mapOf(
        "Flatten clean cardboard; bundle oversized pieces beside the cart." to "干净纸箱压扁；太大的捆好，放在桶旁边。",
        "Greasy pizza boxes go in the green compost cart." to "油披萨盒放进绿色堆肥桶。",
        "Clean paper and mail go in the blue recycling cart." to "干净的纸和信件放进蓝色回收桶。",
        "Recycle the box; remove the plastic liner first." to "盒子可以回收；先取出塑料内袋。",
        "Clean paper bags go in recycling." to "干净纸袋放进回收桶。",
        "Bag shredded paper first, then put it in recycling." to "碎纸先装袋，再放进回收桶。",
        "Used paper towels and napkins go in compost." to "用过的纸巾和餐巾放进堆肥桶。",
        "Used tissues go in the compost cart." to "用过的面纸放进堆肥桶。",
        "Food-soiled paper cups go in the compost cart." to "沾了食物的纸杯放进堆肥桶。",
        "Food-soiled paper plates go in the compost cart." to "沾了食物的纸盘放进堆肥桶。",
        "Compost paper take-out boxes without plastic lining." to "没有塑料内层的纸外卖盒放进堆肥桶。",
        "Coffee grounds and paper filters go in compost." to "咖啡渣和纸滤杯放进堆肥桶。",
        "Paper tea bags go in the compost cart." to "纸茶包放进堆肥桶。",
        "Paperback and hardcover books go in recycling." to "平装和精装书放进回收桶。",
        "Empty plastic bottles go in the blue cart." to "空塑料瓶放进蓝桶。",
        "Empty plastic jugs go in the blue cart." to "空塑料壶放进蓝桶。",
        "Empty, scraped plastic tubs go in recycling." to "刮干净的空塑料盒放进回收桶。",
        "Plastic containers go in recycling; empty and clean." to "塑料盒放进回收桶；先倒空并弄干净。",
        "Empty cold-drink plastic cups, then put them in the blue recycling cart." to "先倒空冷饮塑料杯，再放进蓝色回收桶。",
        "Plastic containers go in recycling; scrape out food." to "塑料盒放进回收桶；先把食物刮掉。",
        "Bundle clean, dry bags into one tied bag, then recycle." to "干净干燥的袋子捆成一袋、扎好，再回收。",
        "Bag bubble wrap with other clean film, then blue cart." to "气泡膜和别的干净薄膜装在一起，放进蓝桶。",
        "Plastic utensils go in the landfill cart." to "塑料餐具放进填埋桶。",
        "Straws go in the landfill cart." to "吸管放进填埋桶。",
        "Chip bags and wrappers go in the landfill cart." to "薯片袋和包装纸放进填埋桶。",
        "\"Compostable\" plastics go in landfill, not compost." to "标了可堆肥的塑料放进填埋桶，不要放堆肥桶。",
        "Foam and polystyrene go in the landfill cart." to "泡沫和聚苯乙烯放进填埋桶。",
        "Foam packing and peanuts go in the landfill cart." to "泡沫包装和泡沫粒放进填埋桶。",
        "Empty aluminum cans go in the blue cart." to "空铝罐放进蓝桶。",
        "Empty, scraped metal cans go in recycling." to "刮干净的空金属罐放进回收桶。",
        "Recycle foil only if it has no food on it." to "锡纸只有完全没有食物才能回收。",
        "Recycle only when completely empty." to "必须完全倒空才能回收。",
        "Empty glass bottles go in the blue cart." to "空玻璃瓶放进蓝桶。",
        "Empty, scraped glass jars go in recycling." to "刮干净的空玻璃罐放进回收桶。",
        "Broken glass goes in the landfill cart." to "碎玻璃放进填埋桶。",
        "Ceramics go in the landfill cart." to "陶瓷放进填埋桶。",
        "Food scraps go in the green compost cart." to "厨余放进绿色堆肥桶。",
        "Meat scraps, including bones, go in the compost cart." to "肉和骨头放进堆肥桶。",
        "Leaves, grass and branches go in the compost cart." to "树叶、草和树枝放进堆肥桶。",
        "Flowers and floral trimmings go in compost." to "花和修剪下来的花枝放进堆肥桶。",
        "Set out sealed cooking-oil jugs with your carts on collection day." to "食用油装进密封壶，收垃圾那天和桶一起放出去。",
        "Wood and bamboo utensils go in the compost cart." to "木筷和竹筷放进堆肥桶。",
        "Tape ends, seal in clear bag, set on recycling cart." to "两端用胶带封住，装进透明袋，放在回收桶上。",
        "Illegal in carts; free Recology on-call pickup: 408-725-4020." to "不能放进门口的桶。Recology 免费上门收：408-725-4020。",
        "Sealed bag on top of recycling cart, or drop off via hhw.org." to "密封袋放在回收桶上面，或按 hhw.org 交出去。",
        "Hazardous waste: book free drop-off at hhw.org." to "有害垃圾：在 hhw.org 预约免费交投。",
        "Free PaintCare take-back, or book drop-off at hhw.org." to "油漆可交给 PaintCare，或在 hhw.org 预约交投。",
        "Cleaners are hazardous waste: book free drop-off at hhw.org." to "清洁剂是有害垃圾：在 hhw.org 预约免费交投。",
        "Never trash; drop off or mail back via med-project.org." to "不要当普通垃圾。交投或按 med-project.org 寄回。",
        "Illegal in carts; seal in biohazard container, use take-back." to "不能放进门口的桶。装进生物危害容器，走回收点。",
        "Diapers go in the landfill cart." to "纸尿裤放进填埋桶。",
        "Pet waste goes in the landfill cart." to "宠物粪便放进填埋桶。",
        "Cat litter goes in the landfill cart." to "猫砂放进填埋桶。",
        "Disposable masks go in the landfill cart." to "一次性口罩放进填埋桶。",
        "Disposable gloves go in the landfill cart." to "一次性手套放进填埋桶。",
        "Textiles, leather and hangers go in the landfill cart." to "纺织品、皮革和衣架放进填埋桶。",
        "Garden hoses go in the landfill cart." to "花园水管放进填埋桶。",
        "Wax-lined frozen food boxes go in the landfill cart." to "有蜡层的冷冻食品盒放进填埋桶。",
        "Scrape the food into the compost cart first, then scan the empty container." to "先把食物倒进堆肥桶，再看空盒子。",
        "Cut boxes small enough to fit loosely in the cart." to "纸箱剪到能松松放进桶里。",
        "Greasy boxes go in garbage; recycle clean lids." to "油盒子放进垃圾桶；干净的盖子可以回收。",
        "Recycle clean paper; no foil, grease or food residue." to "干净的纸可以回收；不要有锡纸、油或食物残渣。",
        "Recycle clean boxes; liners and soiled parts don't go in." to "干净盒子可以回收；内袋和脏的部分不要放进去。",
        "Recycle clean paper bags; glued-on handles are OK." to "干净纸袋可以回收；粘上去的提手可以留着。",
        "Put shreds in a clear bag, tie it, then recycle." to "碎纸装进透明袋、扎好，再回收。",
        "Garbage cart; San José sorts out soiled paper for composting." to "放进垃圾桶。圣何塞会从垃圾里分出脏纸去做堆肥。",
        "Used tissues go in the garbage; never flush them." to "用过的面纸放进垃圾桶，不要冲进马桶。",
        "Plastic-lined cups go in garbage; recycle the cardboard sleeve." to "有塑料内膜的杯子放进垃圾桶；纸套可以回收。",
        "Food-soiled take-out boxes go in the garbage." to "沾了食物的外卖盒放进垃圾桶。",
        "Empty cartons, then recycle; caps go in the garbage." to "纸盒倒空后回收；盖子放进垃圾桶。",
        "Juice boxes go in recycling; straws go in garbage." to "果汁盒放进回收；吸管放进垃圾桶。",
        "Receipts contain BPA and can't be recycled; garbage." to "收据含 BPA，不能回收，放进垃圾桶。",
        "Coffee grounds and paper filters go in the garbage cart." to "咖啡渣和纸滤杯放进垃圾桶。",
        "Tea bags can contain plastic; put them in the garbage." to "茶包可能含塑料，放进垃圾桶。",
        "Recycle books; donate ones in good condition." to "书可以回收；完好的可以捐出去。",
        "Empty plastic bottles, then recycle; no rinsing needed." to "塑料瓶倒空后回收，不用冲洗。",
        "Empty jugs, no rinse needed; caps can stay on." to "壶倒空即可，不用冲洗；盖子可以拧上。",
        "Empty and scrape tubs, then recycle." to "盒子倒空、刮干净，再回收。",
        "Recycle if marked #1-#5 or #7; unmarked, #6 or compostable: garbage." to "标了 #1–#5 或 #7 的可以回收；没标号、#6 或可堆肥塑料放进垃圾桶。",
        "Recycle empty cups marked #1-#5 or #7; #6 or compostable: garbage." to "空杯子标了 #1–#5 或 #7 可以回收；#6 或可堆肥塑料放进垃圾桶。",
        "Empty and scrape, then recycle; not if compostable plastic." to "倒空、刮干净再回收；可堆肥塑料不要放。",
        "Not curbside recyclable; garbage, or clean bags to store drop-off." to "门口不收。放进垃圾桶，或把干净袋子交到商店回收点。",
        "Take clean wrap to a plastic bag drop-off; otherwise garbage." to "干净保鲜膜交到塑料袋回收点，否则放进垃圾桶。",
        "Too small to recycle; plastic utensils go in garbage." to "太小，不能回收。塑料餐具放进垃圾桶。",
        "Straws go in the garbage." to "吸管放进垃圾桶。",
        "Mixed-material bags can't be recycled; garbage." to "混合材料的袋子不能回收，放进垃圾桶。",
        "\"Compostable\" plastics must go in the garbage." to "标了可堆肥的塑料必须放进垃圾桶。",
        "Foam containers aren't recyclable here, even clean." to "这里泡沫盒不能回收，干净的也不行。",
        "Bag packing peanuts, tie shut, put in garbage." to "泡沫粒装袋扎紧，放进垃圾桶。",
        "Loose caps: garbage. Caps screwed onto bottles can be recycled." to "散盖放进垃圾桶。拧在瓶子上的盖子可以一起回收。",
        "Pods are too small to recycle curbside; garbage." to "咖啡胶囊太小，门口不收，放进垃圾桶。",
        "Drink pouches go in the garbage." to "饮料软袋放进垃圾桶。",
        "Toothpaste tubes go in the garbage." to "牙膏管放进垃圾桶。",
        "Manual toothbrushes: garbage. Electric ones are e-waste." to "普通牙刷放进垃圾桶。电动牙刷是电子垃圾。",
        "Recycle hard plastic toys; ones with electronics are e-waste." to "硬塑料玩具可以回收；带电子的是电子垃圾。",
        "Empty any residue, then recycle." to "残渣倒空后再回收。",
        "Empty and scrape cans; labels can stay on." to "罐子倒空、刮干净；标签可以留着。",
        "Clean foil only; roll into a ball at least 2 inches wide." to "只回收干净锡纸；揉成至少 2 英寸宽的球。",
        "Empty and scrape trays; traces of food are OK." to "托盘倒空、刮一刮；留一点食物痕迹可以。",
        "Hazardous waste unless completely empty; empty cans go in recycling." to "没倒空就是有害垃圾；完全空的罐子可以回收。",
        "Empty, remove caps, then recycle; blue glass is not accepted." to "倒空、取下盖子再回收；蓝色玻璃不收。",
        "Scrape jars empty and take off lids, then recycle." to "罐子刮空、取下盖子，再回收。",
        "Bottle and jar shards only; other broken glass: wrap, garbage." to "只收瓶罐碎片；别的碎玻璃包好，放进垃圾桶。",
        "Ceramic dishes go in the garbage." to "陶瓷餐具放进垃圾桶。",
        "Garbage cart; San José recovers food from garbage for composting." to "放进垃圾桶。圣何塞会从垃圾里回收食物去做堆肥。",
        "Bones go in the garbage cart." to "骨头放进垃圾桶。",
        "Yard trimmings cart or pile; keep produce and dog poop bags out." to "放进庭院桶或庭院堆；不要放菜叶和狗粪袋。",
        "Flowers go with yard trimmings; remove packaging first." to "花放进庭院桶；先去掉包装。",
        "Up to 1 quart: cool, seal in can or jar, garbage. More: hazardous." to "不超过 1 夸脱：放凉，密封在罐里，放进垃圾桶。更多就是有害垃圾。",
        "Garbage cart; wooden chopsticks are sorted out and composted." to "放进垃圾桶。木筷会被分出来做堆肥。",
        "Banned from carts; take to County household hazardous waste." to "不能放进门口的桶。交到县里的家庭有害垃圾点。",
        "E-waste: County Household Hazardous Waste Program; never in carts." to "电子垃圾：县家庭有害垃圾项目。不要放进门口的桶。",
        "E-waste: County Household Hazardous Waste Program." to "电子垃圾：县家庭有害垃圾项目。",
        "Hazardous waste: County HHW program or a mail-back kit." to "有害垃圾：县 HHW 项目，或用寄回套装。",
        "LEDs contain lead and arsenic; dispose as hazardous waste." to "LED 含铅和砷，按有害垃圾处理。",
        "Wrap and put in garbage; don't recycle with glass." to "包好放进垃圾桶；不要和玻璃一起回收。",
        "Hazardous waste, free County drop-off; dried latex can go in garbage." to "有害垃圾，县里免费交投；干透的乳胶漆可以放进垃圾桶。",
        "Leftover cleaners are hazardous waste; empty bottles are often recyclable." to "没用完的清洁剂是有害垃圾；空瓶常常可以回收。",
        "Never trash or flush; use a drop-off bin, hhw.org or mailback." to "不要当普通垃圾，也不要冲掉。用回收箱、hhw.org 或寄回。",
        "Seal in a biohazard container; County HHW or drop-off site." to "装进生物危害容器；交县 HHW 或指定点。",
        "Never in carts, fire risk; County hazardous waste drop-off." to "不要放进门口的桶，有起火风险。交县有害垃圾点。",
        "Bag disposable diapers, then put in the garbage." to "纸尿裤装袋，再放进垃圾桶。",
        "Bag animal waste, then garbage; not with yard trimmings." to "动物粪便装袋后放进垃圾桶；不要放庭院桶。",
        "Bag cat litter, then put in the garbage." to "猫砂装袋，再放进垃圾桶。",
        "Masks go in the garbage; snip the straps." to "口罩放进垃圾桶；先剪断带子。",
        "Disposable gloves go in the garbage." to "一次性手套放进垃圾桶。",
        "Donate wearable items; otherwise garbage." to "还能穿的捐出去；否则放进垃圾桶。",
        "Donate usable shoes; otherwise garbage. Light-up shoes are hazardous." to "还能穿的鞋捐出去；否则放进垃圾桶。会发光的鞋是有害垃圾。",
        "Cigarette butts go in the garbage." to "烟头放进垃圾桶。",
        "Wipes go in the garbage; never flush them." to "湿巾放进垃圾桶，不要冲进马桶。",
        "Hoses jam recycling equipment; always garbage." to "水管会卡住回收设备，一律放进垃圾桶。",
        "Only clean, dry paper egg cartons go in recycling." to "只有干净干燥的纸蛋盒可以回收。",
        "Foam (#6) egg cartons go in the garbage." to "泡沫（#6）蛋盒放进垃圾桶。",
        "Recycle if no food residue; otherwise garbage." to "没有食物残渣就可以回收；否则放进垃圾桶。",
        "Scrape the food into the garbage cart first, then scan the empty container." to "先把食物倒进垃圾桶，再看空盒子。",
        "Couldn't tell what it is. Try closer." to "看不出来。再靠近一点。",
        "Two things in the photo. Hold up one." to "照片里有两样。只拿一样。",
        "Type your own key in the phone app." to "在手机上填你自己的千问密钥。",
        "Phone is offline" to "手机没联网",
        "Cloud didn't answer. Tap to retry." to "云端没有回应。再按一下。",
        "Flatten clean cardboard so it fits in the blue cart." to "干净纸箱压扁，放进蓝桶。",
        "Greasy pizza boxes go in the green cart." to "油披萨盒放进绿桶。",
        "Clean newspaper and envelopes go in the blue cart." to "干净报纸和信封放进蓝桶。",
        "Cereal and tissue boxes go in the blue cart." to "麦片盒和纸巾盒放进蓝桶。",
        "Clean paper bags go in the blue cart." to "干净纸袋放进蓝桶。",
        "Tie shredded paper in a clear bag, then recycle." to "碎纸装进透明袋扎好，再回收。",
        "Used napkins and paper towels go in the green cart." to "用过的餐巾和纸巾放进绿桶。",
        "Used tissues go in the green cart." to "用过的面纸放进绿桶。",
        "Paper cups go in the green cart." to "纸杯放进绿桶。",
        "Used paper plates go in the green cart." to "用过的纸盘放进绿桶。",
        "Food-soiled paper take-out containers go in the green cart." to "沾了食物的纸外卖盒放进绿桶。",
        "Milk, juice, and ice cream cartons go in the green cart." to "牛奶盒、果汁盒和冰淇淋盒放进绿桶。",
        "Juice boxes and soup cartons go in the black cart." to "果汁盒和汤盒放进黑桶。",
        "Thermal receipts go in the black cart." to "热敏收据放进黑桶。",
        "Coffee grounds and filters go in the green cart." to "咖啡渣和滤纸放进绿桶。",
        "Non-plastic tea bags go in the green cart." to "不含塑料的茶包放进绿桶。",
        "Books go in the blue cart." to "书放进蓝桶。",
        "Empty yogurt cups and tubs go in the blue cart." to "空酸奶杯和塑料盒放进蓝桶。",
        "Empty plastic food containers go in the blue cart." to "空塑料食物盒放进蓝桶。",
        "Empty rigid take-out containers go in the blue cart." to "空的硬塑料外卖盒放进蓝桶。",
        "Bag clean bubble wrap, then put it in the blue cart." to "干净气泡膜先装袋，再放进蓝桶。",
        "Plastic utensils go in the black cart." to "塑料餐具放进黑桶。",
        "Plastic straws go in the black cart." to "塑料吸管放进黑桶。",
        "Chip bags and wrappers go in the black cart." to "薯片袋和包装纸放进黑桶。",
        "Only plastic labeled COMPOSTABLE goes in the green cart." to "只有标了 COMPOSTABLE 的塑料放进绿桶。",
        "Foam cups, plates, and meat trays go in the black cart." to "泡沫杯、泡沫盘和肉托放进黑桶。",
        "Foam packing and peanuts go in the black cart." to "泡沫包装和泡沫粒放进黑桶。",
        "Lids and caps go in the blue cart." to "盖子放进蓝桶。",
        "Coffee pods go in the black cart." to "咖啡胶囊放进黑桶。",
        "Foil drink pouches go in the black cart." to "铝箔饮料袋放进黑桶。",
        "Toothpaste tubes go in the black cart." to "牙膏管放进黑桶。",
        "Hard plastic toys go in the blue cart." to "硬塑料玩具放进蓝桶。",
        "Empty food and drink cans go in the blue cart." to "空的食品罐和饮料罐放进蓝桶。",
        "Empty food cans go in the blue cart." to "空食品罐放进蓝桶。",
        "Foil, trays, and pans go in the blue cart." to "铝箔、托盘和烤盘放进蓝桶。",
        "Foil trays and pans go in the blue cart." to "铝箔托盘和烤盘放进蓝桶。",
        "Glass bottles and jars go in the blue cart, not blue or red glass." to "玻璃瓶和玻璃罐放进蓝桶，蓝色和红色玻璃不行。",
        "Bag broken glass, then put it in the black cart." to "碎玻璃装袋，再放进黑桶。",
        "Drinking glasses and stemware go in the black cart." to "玻璃杯和高脚杯放进黑桶。",
        "Ceramics and vases go in the black cart." to "陶瓷和花瓶放进黑桶。",
        "Food scraps go in the green cart." to "食物残渣放进绿桶。",
        "Scrape the food into the green cart first, then scan the empty container." to "先把食物倒进绿桶，再看空盒子。",
        "Meat and bones go in the green cart." to "肉和骨头放进绿桶。",
        "Leaves, grass, and branches go in the green cart." to "树叶、草和树枝放进绿桶。",
        "Flowers and plants go in the green cart." to "花和植物放进绿桶。",
        "Cooking oil and grease do not go in the carts." to "食用油和油脂不要放进门口的桶。",
        "Batteries cannot go in any cart." to "电池不能放进任何桶。",
        "Fluorescent bulbs cannot go in the carts." to "荧光灯不能放进门口的桶。",
        "LED bulbs cannot go in the carts." to "LED 灯不能放进门口的桶。",
        "Incandescent and halogen bulbs go in the black cart." to "白炽灯和卤素灯放进黑桶。",
        "Medications cannot go in the carts." to "药品不能放进门口的桶。",
        "Sharps and syringes cannot go in the carts." to "针头和注射器不能放进门口的桶。",
        "Propane tanks cannot go in the carts." to "丙烷罐不能放进门口的桶。",
        "Diapers go in the black cart." to "纸尿裤放进黑桶。",
        "Pet waste goes in the black cart." to "宠物粪便放进黑桶。",
        "Kitty litter goes in the black cart." to "猫砂放进黑桶。",
        "Face masks go in the black cart." to "口罩放进黑桶。",
        "Latex and nitrile gloves go in the black cart." to "乳胶和丁腈手套放进黑桶。",
        "Clothing and bedding go in the black cart." to "衣物和床品放进黑桶。",
        "Garden hoses go in the black cart." to "花园水管放进黑桶。",
        "Clean paper egg cartons go in the blue cart." to "干净纸蛋盒放进蓝桶。",
        "Foam egg cartons go in the black cart." to "泡沫蛋盒放进黑桶。",
        "Frozen food packaging goes in the blue cart." to "冷冻食品包装放进蓝桶。",
        "Flatten cardboard and paper boxes for the blue cart." to "纸箱和纸盒压扁，放进蓝桶。",
        "Pizza boxes go in the green cart." to "披萨盒放进绿桶。",
        "Junk mail and catalogs go in the blue cart." to "广告信和目录放进蓝桶。",
        "Paper boxes go in the blue cart." to "纸盒放进蓝桶。",
        "Put shredded paper in a paper bag, then the blue cart." to "碎纸装进纸袋，再放进蓝桶。",
        "Food-soiled napkins and towels go in the green cart." to "沾了食物的餐巾和纸巾放进绿桶。",
        "Paper plates and cups go in the green cart." to "纸盘和纸杯放进绿桶。",
        "Paper takeout containers go in the green cart." to "纸外卖盒放进绿桶。",
        "Dairy cartons go in the blue cart, not the green cart." to "牛奶盒放进蓝桶，不要放绿桶。",
        "Juice, soup, and soy-milk boxes go in the blue cart." to "果汁盒、汤盒和豆奶盒放进蓝桶。",
        "Tea bags go in the green cart." to "茶包放进绿桶。",
        "Books up to 40 pounds go in the blue cart." to "40 磅以内的书放进蓝桶。",
        "Plastic bottles and jars go in the blue cart." to "塑料瓶和塑料罐放进蓝桶。",
        "Plastic tubs and trays go in the blue cart." to "塑料盒和托盘放进蓝桶。",
        "Stuff bags into one bag, tie it, then the blue cart." to "袋子塞进一个袋子、扎好，再放进蓝桶。",
        "Plastic film and wrap go in the gray cart." to "塑料薄膜和保鲜膜放进灰桶。",
        "Plastic plates and utensils go in the gray cart." to "塑料盘和餐具放进灰桶。",
        "Plastic straws and stir sticks go in the gray cart." to "塑料吸管和搅拌棒放进灰桶。",
        "Foam and styrofoam go in the gray cart." to "泡沫放进灰桶。",
        "Toothpaste tubes go in the gray cart." to "牙膏管放进灰桶。",
        "Toys that cannot be donated go in the gray cart." to "不能捐赠的玩具放进灰桶。",
        "Cans and pans go in the blue cart." to "罐子和烤盘放进蓝桶。",
        "Empty aerosol cans go in the blue cart." to "空喷雾罐放进蓝桶。",
        "Glass bottles and jars go in the blue cart." to "玻璃瓶和玻璃罐放进蓝桶。",
        "Dishes, bowls, and cups go in the gray cart." to "盘子、碗和杯子放进灰桶。",
        "Ceramics go in the gray cart." to "陶瓷放进灰桶。",
        "Food scraps, including peels and rinds, go in the green cart." to "食物残渣，包括果皮，放进绿桶。",
        "Leaves, grass, and small branches go in the green cart." to "树叶、草和小树枝放进绿桶。",
        "Flowers and leaves go in the green cart." to "花和树叶放进绿桶。",
        "Seal cooking oil and set it beside the cart, not in it." to "食用油密封，放在桶旁边，不要放进桶里。",
        "Wooden chopsticks go in the green cart." to "木筷放进绿桶。",
        "Bag batteries and set them on the blue cart, not in it." to "电池装袋，放在蓝桶上面，不要放进桶里。",
        "Bag phones on the blue cart; take other electronics to e-waste." to "手机装袋放在蓝桶上；别的电子产品走电子垃圾。",
        "Bag fluorescent bulbs and set them on the blue cart, not in it." to "荧光灯装袋，放在蓝桶上面，不要放进桶里。",
        "Light bulbs other than fluorescent go in the gray cart." to "荧光灯以外的灯泡放进灰桶。",
        "Set water-based paint beside the cart; oil-based goes to PaintCare." to "水性漆放在桶旁边；油性漆交给 PaintCare。",
        "Medications cannot go in any cart." to "药品不能放进任何桶。",
        "Sharps cannot go in any cart." to "针头不能放进任何桶。",
        "Propane tanks cannot go in any cart." to "丙烷罐不能放进任何桶。",
        "Diapers go in the gray cart." to "纸尿裤放进灰桶。",
        "Bag pet waste, then the gray cart." to "宠物粪便装袋，再放进灰桶。",
        "Bag litter, then put it in the gray cart." to "猫砂装袋，再放进灰桶。",
        "Clothing that cannot be donated goes in the gray cart." to "不能捐赠的衣物放进灰桶。",
        "Shoes that cannot be donated go in the gray cart." to "不能捐赠的鞋放进灰桶。",
        "Garden and rubber hoses go in the gray cart." to "花园水管和橡胶管放进灰桶。",
    )

    /** Short lens name. The English catalog name is what the model sees; this is display only. */
    private val ITEM_ZH = mapOf(
        "cardboard_box" to "纸箱",
        "pizza_box_greasy" to "空油披萨盒",
        "paper_mixed" to "纸张",
        "paperboard_box" to "纸盒",
        "paper_bag" to "纸袋",
        "shredded_paper" to "碎纸",
        "paper_towel_napkin" to "纸巾",
        "tissue" to "面纸",
        "paper_cup" to "纸杯",
        "paper_plate_used" to "纸盘",
        "paper_takeout" to "纸外卖盒",
        "carton" to "牛奶盒",
        "aseptic_carton" to "利乐包",
        "receipt" to "小票",
        "coffee_grounds_filter" to "咖啡渣",
        "tea_bag" to "茶包",
        "book" to "书",
        "plastic_bottle" to "塑料瓶",
        "plastic_jug" to "塑料壶",
        "plastic_tub" to "塑料盒",
        "plastic_clamshell" to "塑料翻盖盒",
        "plastic_cup" to "塑料杯",
        "plastic_takeout" to "塑料外卖盒",
        "plastic_bag" to "塑料袋",
        "bubble_wrap" to "气泡膜",
        "plastic_utensils" to "塑料餐具",
        "straw" to "吸管",
        "snack_wrapper" to "零食袋",
        "compostable_plastic" to "可堆肥塑料",
        "foam_food_container" to "泡沫盒",
        "foam_packaging" to "泡沫包装",
        "plastic_cap" to "瓶盖",
        "coffee_pod" to "咖啡胶囊",
        "drink_pouch" to "饮料袋",
        "toothpaste_tube" to "牙膏管",
        "toothbrush" to "牙刷",
        "plastic_toy" to "塑料玩具",
        "aluminum_can" to "铝罐",
        "food_can" to "铁罐",
        "aluminum_foil" to "铝箔",
        "aluminum_tray" to "铝箔盘",
        "aerosol_can" to "喷雾罐",
        "glass_bottle" to "玻璃瓶",
        "glass_jar" to "玻璃罐",
        "broken_glass" to "碎玻璃",
        "drinking_glass" to "玻璃杯",
        "ceramic" to "陶瓷",
        "food_scraps" to "食物残渣",
        "food_in_container" to "还剩食物",
        "bones" to "骨头",
        "yard_trimmings" to "落叶树枝",
        "flowers" to "鲜花",
        "cooking_oil" to "食用油",
        "wooden_chopsticks" to "木筷",
        "battery" to "电池",
        "phone_electronics" to "电子产品",
        "cords_cables" to "电线",
        "bulb_fluorescent" to "荧光灯",
        "bulb_led" to "LED灯",
        "bulb_incandescent" to "白炽灯",
        "paint" to "油漆",
        "cleaning_product" to "清洁剂",
        "medicine" to "药品",
        "sharps" to "针头",
        "propane_cylinder" to "气罐",
        "diaper" to "纸尿裤",
        "pet_waste" to "宠物粪便",
        "kitty_litter" to "猫砂",
        "face_mask" to "口罩",
        "disposable_gloves" to "手套",
        "textiles" to "衣物",
        "shoes" to "鞋",
        "cigarette" to "烟头",
        "wipes" to "湿巾",
        "garden_hose" to "水管",
        "egg_carton_paper" to "纸蛋盒",
        "egg_carton_foam" to "泡沫蛋盒",
        "frozen_food_box" to "冷冻盒",
    )
}
